# Use the official Python image
FROM python:3.9

# python envs
ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

RUN apt-get update \
    && apt-get install -y gettext libgettextpo-dev

# upgrade pip
RUN pip install --upgrade pip

# Set the working directory
WORKDIR /app

# Install dependencies
COPY ./FDS/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the project files
COPY /FDS .
